# SPDX-FileCopyrightText: 2026 Sri Rang
# SPDX-License-Identifier: GPL-3.0-or-later

version = 1

[[annotations]]
path = ".kateproject"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Sri Rang"
SPDX-License-Identifier = "GPL-3.0-or-later"
